# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datoscantidad.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!


from GUIs import iconos_rc

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 673)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/cola.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.tituloLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tituloLabel.sizePolicy().hasHeightForWidth())
        self.tituloLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.tituloLabel.setFont(font)
        self.tituloLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloLabel.setObjectName("tituloLabel")
        self.horizontalLayout_6.addWidget(self.tituloLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem5)
        self.bAnadirExp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAnadirExp.sizePolicy().hasHeightForWidth())
        self.bAnadirExp.setSizePolicy(sizePolicy)
        self.bAnadirExp.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bAnadirExp.setFont(font)
        self.bAnadirExp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/iconos/678092-sign-add-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAnadirExp.setIcon(icon1)
        self.bAnadirExp.setObjectName("bAnadirExp")
        self.verticalLayout_10.addWidget(self.bAnadirExp)
        self.bEditarExp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bEditarExp.sizePolicy().hasHeightForWidth())
        self.bEditarExp.setSizePolicy(sizePolicy)
        self.bEditarExp.setMinimumSize(QtCore.QSize(50, 40))
        self.bEditarExp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/iconos/edit-icon-11-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bEditarExp.setIcon(icon2)
        self.bEditarExp.setObjectName("bEditarExp")
        self.verticalLayout_10.addWidget(self.bEditarExp)
        self.bEliminarExp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bEliminarExp.sizePolicy().hasHeightForWidth())
        self.bEliminarExp.setSizePolicy(sizePolicy)
        self.bEliminarExp.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bEliminarExp.setFont(font)
        self.bEliminarExp.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/iconos/627249-delete3-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bEliminarExp.setIcon(icon3)
        self.bEliminarExp.setObjectName("bEliminarExp")
        self.verticalLayout_10.addWidget(self.bEliminarExp)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_10.addItem(spacerItem6)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        self.tablaExp = QtWidgets.QTableView(self.centralwidget)
        self.tablaExp.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablaExp.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablaExp.setObjectName("tablaExp")
        self.horizontalLayout_12.addWidget(self.tablaExp)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBoxEditarExp = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxEditarExp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEditarExp.sizePolicy().hasHeightForWidth())
        self.groupBoxEditarExp.setSizePolicy(sizePolicy)
        self.groupBoxEditarExp.setMinimumSize(QtCore.QSize(280, 180))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxEditarExp.setFont(font)
        self.groupBoxEditarExp.setObjectName("groupBoxEditarExp")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBoxEditarExp)
        self.formLayout_3.setObjectName("formLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_3.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        self.sbCantServ = QtWidgets.QSpinBox(self.groupBoxEditarExp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCantServ.sizePolicy().hasHeightForWidth())
        self.sbCantServ.setSizePolicy(sizePolicy)
        self.sbCantServ.setMinimum(1)
        self.sbCantServ.setObjectName("sbCantServ")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbCantServ)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem9)
        self.labelCantUsuarios = QtWidgets.QLabel(self.groupBoxEditarExp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCantUsuarios.sizePolicy().hasHeightForWidth())
        self.labelCantUsuarios.setSizePolicy(sizePolicy)
        self.labelCantUsuarios.setObjectName("labelCantUsuarios")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelCantUsuarios)
        self.labelCantServ = QtWidgets.QLabel(self.groupBoxEditarExp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCantServ.sizePolicy().hasHeightForWidth())
        self.labelCantServ.setSizePolicy(sizePolicy)
        self.labelCantServ.setObjectName("labelCantServ")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCantServ)
        self.sbCantUsuarios = QtWidgets.QSpinBox(self.groupBoxEditarExp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCantUsuarios.sizePolicy().hasHeightForWidth())
        self.sbCantUsuarios.setSizePolicy(sizePolicy)
        self.sbCantUsuarios.setMinimum(1)
        self.sbCantUsuarios.setObjectName("sbCantUsuarios")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbCantUsuarios)
        self.verticalLayout_15.addWidget(self.groupBoxEditarExp)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem10 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.bOkEditarExp = QtWidgets.QPushButton(self.centralwidget)
        self.bOkEditarExp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOkEditarExp.sizePolicy().hasHeightForWidth())
        self.bOkEditarExp.setSizePolicy(sizePolicy)
        self.bOkEditarExp.setMinimumSize(QtCore.QSize(50, 40))
        self.bOkEditarExp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconos/iconos/ok-icon-success-19.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bOkEditarExp.setIcon(icon4)
        self.bOkEditarExp.setObjectName("bOkEditarExp")
        self.horizontalLayout_16.addWidget(self.bOkEditarExp)
        spacerItem11 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_12.addLayout(self.verticalLayout_15)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem16 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem16)
        self.bAnadirCorrida = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAnadirCorrida.sizePolicy().hasHeightForWidth())
        self.bAnadirCorrida.setSizePolicy(sizePolicy)
        self.bAnadirCorrida.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bAnadirCorrida.setFont(font)
        self.bAnadirCorrida.setText("")
        self.bAnadirCorrida.setIcon(icon1)
        self.bAnadirCorrida.setObjectName("bAnadirCorrida")
        self.verticalLayout_9.addWidget(self.bAnadirCorrida)
        self.bEditarCorrida = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bEditarCorrida.sizePolicy().hasHeightForWidth())
        self.bEditarCorrida.setSizePolicy(sizePolicy)
        self.bEditarCorrida.setMinimumSize(QtCore.QSize(50, 40))
        self.bEditarCorrida.setText("")
        self.bEditarCorrida.setIcon(icon2)
        self.bEditarCorrida.setObjectName("bEditarCorrida")
        self.verticalLayout_9.addWidget(self.bEditarCorrida)
        self.bEliminarCorrida = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bEliminarCorrida.sizePolicy().hasHeightForWidth())
        self.bEliminarCorrida.setSizePolicy(sizePolicy)
        self.bEliminarCorrida.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bEliminarCorrida.setFont(font)
        self.bEliminarCorrida.setText("")
        self.bEliminarCorrida.setIcon(icon3)
        self.bEliminarCorrida.setObjectName("bEliminarCorrida")
        self.verticalLayout_9.addWidget(self.bEliminarCorrida)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_9.addItem(spacerItem17)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.tablaCorridas = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablaCorridas.sizePolicy().hasHeightForWidth())
        self.tablaCorridas.setSizePolicy(sizePolicy)
        self.tablaCorridas.setMinimumSize(QtCore.QSize(290, 240))
        self.tablaCorridas.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablaCorridas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablaCorridas.setObjectName("tablaCorridas")
        self.horizontalLayout_11.addWidget(self.tablaCorridas)
        spacerItem18 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBoxEditarCorrida = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxEditarCorrida.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEditarCorrida.sizePolicy().hasHeightForWidth())
        self.groupBoxEditarCorrida.setSizePolicy(sizePolicy)
        self.groupBoxEditarCorrida.setMinimumSize(QtCore.QSize(280, 180))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxEditarCorrida.setFont(font)
        self.groupBoxEditarCorrida.setObjectName("groupBoxEditarCorrida")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBoxEditarCorrida)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelSemilla = QtWidgets.QLabel(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSemilla.sizePolicy().hasHeightForWidth())
        self.labelSemilla.setSizePolicy(sizePolicy)
        self.labelSemilla.setObjectName("labelSemilla")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSemilla)
        self.lineSemilla = QtWidgets.QLineEdit(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSemilla.sizePolicy().hasHeightForWidth())
        self.lineSemilla.setSizePolicy(sizePolicy)
        self.lineSemilla.setMaxLength(5)
        self.lineSemilla.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineSemilla.setObjectName("lineSemilla")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineSemilla)
        self.labelTasaLleg = QtWidgets.QLabel(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTasaLleg.sizePolicy().hasHeightForWidth())
        self.labelTasaLleg.setSizePolicy(sizePolicy)
        self.labelTasaLleg.setObjectName("labelTasaLleg")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTasaLleg)
        self.lineTasaLleg = QtWidgets.QLineEdit(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineTasaLleg.sizePolicy().hasHeightForWidth())
        self.lineTasaLleg.setSizePolicy(sizePolicy)
        self.lineTasaLleg.setMaxLength(3)
        self.lineTasaLleg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineTasaLleg.setObjectName("lineTasaLleg")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineTasaLleg)
        self.labelTasaServ = QtWidgets.QLabel(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTasaServ.sizePolicy().hasHeightForWidth())
        self.labelTasaServ.setSizePolicy(sizePolicy)
        self.labelTasaServ.setObjectName("labelTasaServ")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelTasaServ)
        self.lineTasaServ = QtWidgets.QLineEdit(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineTasaServ.sizePolicy().hasHeightForWidth())
        self.lineTasaServ.setSizePolicy(sizePolicy)
        self.lineTasaServ.setMaxLength(3)
        self.lineTasaServ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineTasaServ.setObjectName("lineTasaServ")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineTasaServ)
        self.labelUsuariosIni = QtWidgets.QLabel(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUsuariosIni.sizePolicy().hasHeightForWidth())
        self.labelUsuariosIni.setSizePolicy(sizePolicy)
        self.labelUsuariosIni.setObjectName("labelUsuariosIni")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelUsuariosIni)
        self.sbUsuariosIni = QtWidgets.QSpinBox(self.groupBoxEditarCorrida)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbUsuariosIni.sizePolicy().hasHeightForWidth())
        self.sbUsuariosIni.setSizePolicy(sizePolicy)
        self.sbUsuariosIni.setMinimum(0)
        self.sbUsuariosIni.setObjectName("sbUsuariosIni")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sbUsuariosIni)
        self.verticalLayout_14.addWidget(self.groupBoxEditarCorrida)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem19 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem19)
        self.bOkEditarCorrida = QtWidgets.QPushButton(self.centralwidget)
        self.bOkEditarCorrida.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOkEditarCorrida.sizePolicy().hasHeightForWidth())
        self.bOkEditarCorrida.setSizePolicy(sizePolicy)
        self.bOkEditarCorrida.setMinimumSize(QtCore.QSize(50, 40))
        self.bOkEditarCorrida.setText("")
        self.bOkEditarCorrida.setIcon(icon4)
        self.bOkEditarCorrida.setObjectName("bOkEditarCorrida")
        self.horizontalLayout_15.addWidget(self.bOkEditarCorrida)
        spacerItem20 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem20)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem21)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem22)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem23)
        self.bVolver = QtWidgets.QPushButton(self.centralwidget)
        self.bVolver.setMinimumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bVolver.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconos/iconos/btn-blue-arrow-left-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bVolver.setIcon(icon5)
        self.bVolver.setObjectName("bVolver")
        self.horizontalLayout.addWidget(self.bVolver)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem24)
        self.bSimular = QtWidgets.QPushButton(self.centralwidget)
        self.bSimular.setEnabled(False)
        self.bSimular.setMinimumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bSimular.setFont(font)
        self.bSimular.setIcon(icon4)
        self.bSimular.setObjectName("bSimular")
        self.horizontalLayout.addWidget(self.bSimular)
        spacerItem25 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem25)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.bAnadirExp, self.bEliminarExp)
        MainWindow.setTabOrder(self.bEliminarExp, self.tablaExp)
        MainWindow.setTabOrder(self.tablaExp, self.sbCantServ)
        MainWindow.setTabOrder(self.sbCantServ, self.sbCantUsuarios)
        MainWindow.setTabOrder(self.sbCantUsuarios, self.bOkEditarExp)
        MainWindow.setTabOrder(self.bOkEditarExp, self.bAnadirCorrida)
        MainWindow.setTabOrder(self.bAnadirCorrida, self.bEliminarCorrida)
        MainWindow.setTabOrder(self.bEliminarCorrida, self.tablaCorridas)
        MainWindow.setTabOrder(self.tablaCorridas, self.lineSemilla)
        MainWindow.setTabOrder(self.lineSemilla, self.lineTasaLleg)
        MainWindow.setTabOrder(self.lineTasaLleg, self.lineTasaServ)
        MainWindow.setTabOrder(self.lineTasaServ, self.sbUsuariosIni)
        MainWindow.setTabOrder(self.sbUsuariosIni, self.bOkEditarCorrida)
        MainWindow.setTabOrder(self.bOkEditarCorrida, self.bVolver)
        MainWindow.setTabOrder(self.bVolver, self.bSimular)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulador de Colas"))
        self.tituloLabel.setText(_translate("MainWindow", " Ingreso de Datos"))
        self.label.setText(_translate("MainWindow", "Experimentos "))
        self.groupBoxEditarExp.setTitle(_translate("MainWindow", "Editar"))
        self.labelCantUsuarios.setText(_translate("MainWindow", "Cantidad de Usuarios"))
        self.labelCantServ.setText(_translate("MainWindow", "Cantidad de servidores"))
        self.label_2.setText(_translate("MainWindow", "Corridas"))
        self.groupBoxEditarCorrida.setTitle(_translate("MainWindow", "Editar"))
        self.labelSemilla.setText(_translate("MainWindow", "Semilla"))
        self.labelTasaLleg.setText(_translate("MainWindow", "Tasa de llegadas (λ)"))
        self.labelTasaServ.setText(_translate("MainWindow", "Tasa de servicio (µ)"))
        self.labelUsuariosIni.setText(_translate("MainWindow", "Usuarios iniciales"))
        self.bVolver.setText(_translate("MainWindow", "Volver"))
        self.bSimular.setText(_translate("MainWindow", "Simular"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
