# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!


from GUIs import iconos_rc

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 489)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/cola.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWhatsThis("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bAcercaDe = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAcercaDe.sizePolicy().hasHeightForWidth())
        self.bAcercaDe.setSizePolicy(sizePolicy)
        self.bAcercaDe.setMinimumSize(QtCore.QSize(20, 0))
        self.bAcercaDe.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/iconos/questionssvg-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAcercaDe.setIcon(icon1)
        self.bAcercaDe.setIconSize(QtCore.QSize(20, 20))
        self.bAcercaDe.setObjectName("bAcercaDe")
        self.horizontalLayout_3.addWidget(self.bAcercaDe)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.tituloLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tituloLabel.sizePolicy().hasHeightForWidth())
        self.tituloLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.tituloLabel.setFont(font)
        self.tituloLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloLabel.setObjectName("tituloLabel")
        self.horizontalLayout_6.addWidget(self.tituloLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.colaTiempo = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.colaTiempo.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/iconos/time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colaTiempo.setIcon(icon2)
        self.colaTiempo.setObjectName("colaTiempo")
        self.horizontalLayout.addWidget(self.colaTiempo)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.colaCant = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.colaCant.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/iconos/multiple-users-silhouette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colaCant.setIcon(icon3)
        self.colaCant.setObjectName("colaCant")
        self.horizontalLayout.addWidget(self.colaCant)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.groupBoxDefinir = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxDefinir.setFont(font)
        self.groupBoxDefinir.setObjectName("groupBoxDefinir")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxDefinir)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.usuarioLabel = QtWidgets.QLabel(self.groupBoxDefinir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usuarioLabel.sizePolicy().hasHeightForWidth())
        self.usuarioLabel.setSizePolicy(sizePolicy)
        self.usuarioLabel.setObjectName("usuarioLabel")
        self.gridLayout.addWidget(self.usuarioLabel, 3, 1, 1, 1)
        self.servidoresLabel = QtWidgets.QLabel(self.groupBoxDefinir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.servidoresLabel.sizePolicy().hasHeightForWidth())
        self.servidoresLabel.setSizePolicy(sizePolicy)
        self.servidoresLabel.setObjectName("servidoresLabel")
        self.gridLayout.addWidget(self.servidoresLabel, 2, 1, 1, 1)
        self.sistemaLabel = QtWidgets.QLabel(self.groupBoxDefinir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sistemaLabel.sizePolicy().hasHeightForWidth())
        self.sistemaLabel.setSizePolicy(sizePolicy)
        self.sistemaLabel.setObjectName("sistemaLabel")
        self.gridLayout.addWidget(self.sistemaLabel, 1, 1, 1, 1)
        self.usuarioLineEdit = QtWidgets.QLineEdit(self.groupBoxDefinir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usuarioLineEdit.sizePolicy().hasHeightForWidth())
        self.usuarioLineEdit.setSizePolicy(sizePolicy)
        self.usuarioLineEdit.setMaxLength(30)
        self.usuarioLineEdit.setObjectName("usuarioLineEdit")
        self.gridLayout.addWidget(self.usuarioLineEdit, 3, 3, 1, 1)
        self.sistemaLineEdit = QtWidgets.QLineEdit(self.groupBoxDefinir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sistemaLineEdit.sizePolicy().hasHeightForWidth())
        self.sistemaLineEdit.setSizePolicy(sizePolicy)
        self.sistemaLineEdit.setMaxLength(30)
        self.sistemaLineEdit.setObjectName("sistemaLineEdit")
        self.gridLayout.addWidget(self.sistemaLineEdit, 1, 3, 1, 1)
        self.servidorLineEdit = QtWidgets.QLineEdit(self.groupBoxDefinir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.servidorLineEdit.sizePolicy().hasHeightForWidth())
        self.servidorLineEdit.setSizePolicy(sizePolicy)
        self.servidorLineEdit.setMinimumSize(QtCore.QSize(200, 20))
        self.servidorLineEdit.setText("")
        self.servidorLineEdit.setMaxLength(30)
        self.servidorLineEdit.setObjectName("servidorLineEdit")
        self.gridLayout.addWidget(self.servidorLineEdit, 2, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxDefinir)
        spacerItem13 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem14 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.bLimpiar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLimpiar.sizePolicy().hasHeightForWidth())
        self.bLimpiar.setSizePolicy(sizePolicy)
        self.bLimpiar.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bLimpiar.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconos/iconos/Clear-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bLimpiar.setIcon(icon4)
        self.bLimpiar.setIconSize(QtCore.QSize(23, 23))
        self.bLimpiar.setObjectName("bLimpiar")
        self.horizontalLayout_10.addWidget(self.bLimpiar)
        self.bSiguiente = QtWidgets.QPushButton(self.centralwidget)
        self.bSiguiente.setEnabled(False)
        self.bSiguiente.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bSiguiente.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconos/iconos/ok-icon-success-19.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSiguiente.setIcon(icon5)
        self.bSiguiente.setObjectName("bSiguiente")
        self.horizontalLayout_10.addWidget(self.bSiguiente)
        spacerItem16 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem17)
        MainWindow.setCentralWidget(self.centralwidget)
        self.sistemaLabel.setBuddy(self.usuarioLineEdit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.colaTiempo, self.colaCant)
        MainWindow.setTabOrder(self.colaCant, self.sistemaLineEdit)
        MainWindow.setTabOrder(self.sistemaLineEdit, self.servidorLineEdit)
        MainWindow.setTabOrder(self.servidorLineEdit, self.usuarioLineEdit)
        MainWindow.setTabOrder(self.usuarioLineEdit, self.bLimpiar)
        MainWindow.setTabOrder(self.bLimpiar, self.bSiguiente)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulador de Colas"))
        self.tituloLabel.setText(_translate("MainWindow", "Simulador de Colas M/M/S"))
        self.colaTiempo.setText(_translate("MainWindow", "Cola por Tiempo"))
        self.colaCant.setText(_translate("MainWindow", "Cola por Cantidad"))
        self.groupBoxDefinir.setTitle(_translate("MainWindow", "Definir entorno de Simulación"))
        self.usuarioLabel.setText(_translate("MainWindow", "Usuario"))
        self.servidoresLabel.setText(_translate("MainWindow", "Servidor"))
        self.sistemaLabel.setText(_translate("MainWindow", "&Sistema"))
        self.bLimpiar.setText(_translate("MainWindow", "Limpiar"))
        self.bSiguiente.setText(_translate("MainWindow", "Siguiente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
